title: tree

author: Matteo

links:
  github: https://matteo.eu.org
  custom:
    - name: UidGenerator
      URL: https://github.com/wujun234/uid-generator-spring-boot-starter
  
favicon: /favicon.ico

# giscus评论系统在这里配置 https://giscus.app/zh-CN
giscus:
    enable: true
    repo: "lthcweb/lthcweb.github.io"
    repo_id: "MDEwOlJlcG9zaXRvcnkzNjQzMzAzNzQ="
    category_id: "DIC_kwDOFbc9hs4CPQN0"
    reactions_enabled: "0"	 
    emit_metadata: "0"
    input_position: "bottom"	
    theme: "light"
    lang: "zh-CN"

# valine 
valine:
    # 评论
    enableComment: false 
    # 阅读量
    enableCounter: false
    # valine appID
    appID:
    # valine appKey
    appKey:
    placeholder: 请输入评论
    avatar: retro

# 是否开启“不蒜子”统计访问量
busuanzi: false

# 底部版权开始年份
siteStartYear: 2023

####### 站外搜索配置 #####
# 站点如果【被搜索引擎收录】，可以配置通过搜索引擎全站搜索
# searchEngine：搜索引擎，不配置则默认为谷歌，可替换为百度等其他搜索引擎的搜索 URL
#   https://www.baidu.com/s?wd=
#   https://www.google.com/search?q=
# homeHost：要搜索的站点域名，不配置默认取当前页面的域名
searchEngine: https://www.google.com/search?q=
homeHost: matteo.eu.org

tags: true
categories: true

# 左侧导航栏，用文件名还是文章名
sidebar:
  # usePostTitle 为 ture 用文章名，不填或为 false 用文件名
  usePostTitle: false